training:
  experimnet_name: "STIPoser"
  device: "cpu"
  resume: True

  batch_size: 48
  num_worker: 4
  epochs: 200

smpl:
  file: "./artifacts/smpl/SMPL_MALE.pkl"
  reduced_joints: [0, 1, 2, 3, 6, 9, 12, 13, 14, 16, 17]
  ignored_joints: [7, 8, 10, 11, 20, 21, 22, 23]
  imu_joints: [0, 4, 5, 11, 14, 15]
  leaf_joints: [0, 7, 8, 15, 20, 21]

model:
  embed_dim: 256
  avg_kernel: 7
  use_uwb: True
  use_uwb_attn: True
  use_translation: False
  use_imu_aux: True
  adj_path: "./artifacts/adj_matrixes.pt"


optimizer:
  name: "admamw"
  lr: 1e-3
  momentum: 0.9
  betas: [0.9, 0.999]
  weight_decay: 0.05
  grad_norm: 1.0
  schedular: "cos"

dataset:
  dir: "./data"
  seq_length: 300
  overlap: 0

loss:
  aux_weight: 0.1

  out_rot:
    target: "grot"
    indexs: [1, 2, 3, 6, 9, 12, 13, 14, 16, 17]

  out_trans:
    target: "trans"
    
  aux_ivel:
    target: "jvel"
    indexs: [0, 7, 8, 15, 20, 21]

  aux_vel:
    target: "jvel"

# for training dynamic inertia poser.
  aux_fvel:
    target: "jvel"
    indexs: [0, 7, 8, 15]
  
  aux_bvel:
    target: "jvel"
    indexs: [0, 15]

  aux_hvel:
    target: "jvel"
    indexs: [20, 21]