training:
  experimnet_name: "stiposer_dip"
  model_name: "STIPoser"
  device: "cuda"
  resume: False
  epochs: 200
  comet_api_key: "Add your comet api here"

smpl:
  file: "./artifacts/smpl/SMPL_MALE.pkl"
  reduced_joints: [0, 1, 2, 3, 6, 9, 12, 13, 14, 16, 17]
  ignored_joints: [7, 8, 10, 11, 20, 21, 22, 23]
  imu_joints: [0, 4, 5, 15, 18, 19]
  leaf_joints: [0, 7, 8, 15, 20, 21]
  sip_joints: [1, 2, 16, 17]

model:
  embed_dim: 288
  avg_kernel: 7
  use_uwb: False
  use_uwb_attn: False
  use_translation: False
  use_imu_aux: True
  adj_path: "./artifacts/adj_matrixes.pt"


optimizer:
  name: "adamw"
  lr: 0.001
  momentum: 0.9
  adamw_betas: [0.9, 0.999]
  weight_decay: 0.05
  grad_norm: 1.0
  schedular: "cos"
  warmup:
    factor: 0.1
    epochs: 0

dataset:
  dir: "./data"
  seq_length: 300
  overlap: 0
  batch_size: 48
  num_worker: 4
  random_noise:
    std: 0.1
    p: 0.5

loss:
  aux_weight: 1.0
  trans_weight: 1.0
  pose_beta: 0.01
  trans_beta: 0.1
  aux_beta: 0.01

  out_rot:
    target: "grot"
    indexs: [1, 2, 3, 6, 9, 12, 13, 14, 16, 17]
  out_rot_foot:
    target: "grot"
    indexs: [1, 2]
  out_rot_body:
    target: "grot"
    indexs: [3, 6, 9, 12]
  out_rot_hand:
    target: "grot"
    indexs: [13, 14, 16, 17]

  out_trans:
    target: "trans"
    indexs: None
    
  aux_ivel:
    target: "jvel"
    indexs: [0, 7, 8, 15, 20, 21]

  aux_vel:
    target: "jvel"

# for training dynamic inertia poser.
  aux_fvel:
    target: "jvel"
    indexs: [0, 7, 8, 15]
  
  aux_bvel:
    target: "jvel"
    indexs: [0, 15]

  aux_hvel:
    target: "jvel"
    indexs: [20, 21]

famo:
  use: True
  n_tasks: 2
  lr: 0.025
  gamma: float = 0.01,   # the regularization coefficient

data_paths:
  dip: 
    path: "./data/raw data/DIP_IMU"
    set: "Test"
  total capture: 
    path: "./data/raw data/TotalCapture"
    set: "Valid"
  emonike: 
    path: "./data/raw data/EmokineDataset_v1.0/Data/MVNX"
    set: "Train" 
  andy: 
    path: "./data/raw data/MTwAwinda"
    set: "Train" 
  cip: 
    path: "./data/raw data/xens_mnvx/"
    set: "Train" 
  virginia: 
    path: "./data/raw data/mvnx-dataset/"
    set: "Train" 
  unipd: 
    path: "./data/raw data/mvnx-dataset/"
    set: "Train" 
